preload = ["./orchestrator/preload.ts"]
smol = false
logLevel = "warn"

[console]
depth = 3

[install]
saveTextLockfile = true
linkWorkspacePackages = true
auto = "auto"

[test]
smol = true
coverageSkipTestFiles = true

[test.reporter]
junit = "reports/junit.xml"
